# Site/SEO settings
email: hi@dergigi.com
baseurl: ""
permalink: /:title/

name: Gigi
title: Fucking Shitcoins
description: >
  You forced me to pay in fucking shitcoins!
url: https://fuckingshitcoins.com
twitter_username: dergigi
default_img: /assets/images/avatar.png
social:
  - name: twitter
    url: https://twitter.com/FuckingShitcoins
  - name: github
    url: https://github.com/fuckingshitcoins/fuckingshitcoins.github.io
  - name: bitcoin
    url: https://dergigi.com/support

# Author settings
author:
  - name: Gigi
    bio: Bio as in biological?
    url: https://dergigi.com/contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
